fixed indentation

diff --git a/.github/workflows/python-package-conda.yml b/.github/workflows/python-package-conda.yml
--- a/.github/workflows/python-package-conda.yml
+++ b/.github/workflows/python-package-conda.yml
@@ -34,25 +34,25 @@ jobs:
       shell: bash -l {0}
 
     - name: Test with pytest
-        env:
-          SUBJECTS_DIR: ${{ github.workspace }}/test_data/fs
-          MALLOC_TRIM_THRESHOLD_: 0
-          PYTHONUNBUFFERED: 1
-        run: |
-          set +e
-          conda activate lameg
-          wget -q -c https://osf.io/s2ehv/download -O "${{ github.workspace }}/test_data_v2.tar.gz"
-          tar -xzf ${{ github.workspace }}/test_data_v2.tar.gz -C ${{ github.workspace }}
-          rm ${{ github.workspace }}/test_data_v2.tar.gz
+      env:
+        SUBJECTS_DIR: ${{ github.workspace }}/test_data/fs
+        MALLOC_TRIM_THRESHOLD_: 0
+        PYTHONUNBUFFERED: 1
+      run: |
+        set +e
+        conda activate lameg
+        wget -q -c https://osf.io/s2ehv/download -O "${{ github.workspace }}/test_data_v2.tar.gz"
+        tar -xzf ${{ github.workspace }}/test_data_v2.tar.gz -C ${{ github.workspace }}
+        rm ${{ github.workspace }}/test_data_v2.tar.gz
 
-          stdbuf -oL -eL pytest -v -s --color=yes --cov=lameg --cov-report=xml
-          code=$?
+        stdbuf -oL -eL pytest -v -s --color=yes --cov=lameg --cov-report=xml
+        code=$?
 
-          # Fail only on nonzero codes other than segfault (139)
-          if [ $code -ne 0 ] && [ $code -ne 139 ]; then
-            exit $code
-          fi
-        shell: bash -l {0}
+        # Fail only on nonzero codes other than segfault (139)
+        if [ $code -ne 0 ] && [ $code -ne 139 ]; then
+          exit $code
+        fi
+      shell: bash -l {0}
 
     - name: Upload coverage to Codecov
       uses: codecov/codecov-action@v3
